function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 31-May-2022 17:43:12

Fpass1 = 80;     % First Passband Frequency
Fstop1 = 100;    % First Stopband Frequency
Fstop2 = 250;    % Second Stopband Frequency
Fpass2 = 270;    % Second Passband Frequency
Apass1 = 1;      % First Passband Ripple (dB)
Astop  = 60;     % Stopband Attenuation (dB)
Apass2 = 1;      % Second Passband Ripple (dB)
Fs     = 48000;  % Sampling Frequency

h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
    Fstop2, Fpass2, Apass1, Astop, Apass2, Fs);

Hd = design(h, 'butter', ...
    'MatchExactly', 'stopband', ...
    'SystemObject', true);


