.ALIASES
R_R1            R1(1=N00234 2=N01081 )
C_C4            C4(1=0 2=N00305 )
R_R2            R2(1=0 2=N00234 )
R_R3            R3(1=0 2=N00305 )
L_L1            L1(1=N01081 2=VOUT )
V_V1            V1(+=N01081 -=0 )
L_L2            L2(1=VOUT 2=N00659 )
C_C1            C1(1=0 2=VOUT )
C_C2            C2(1=N00659 2=0 )
C_C3            C3(1=N00234 2=N00659 )
Q_Q1            Q1(c=VOUT b=N00234 e=N00305 )
_    _(Vout=VOUT)
.ENDALIASES
