clear;clc;clear;

t1=-2:2;
y1=ones(1, size(t1,2)).*(t1>-1 & t1<1) + 0.*(t1<=-1 & t1>=1);
y1=repmat(y1, 1, 2);
y1f=fftshift(fft(y1));
subplot(3,3,1);
plot(y1);
title('Step Square pulse With (K=4)');
grid on;grid minor;
subplot(3,3,2);
stem(abs(y1f));
title('Fourier Series Coefficients With (K=4)');
grid on;grid minor;
subplot(3,3,3);
plot(y1.*abs(y1f));
title('Fourier Series Transform With (K=4)');
grid on;grid minor;
% ---------------------------------------------------------------
t2=-2:0.2:2;
y2=ones(1, size(t2,2)).*(t2>-1 & t2<1) + 0.*(t2<=-1 & t2>=1);
y2=repmat(y2, 1, 2);
y2f=fftshift(fft(y2));
subplot(3,3,4);
plot(y2);
title('Step Square pulse With (K=20)');
grid on;grid minor;
subplot(3,3,5);
stem(abs(y2f));
title('Fourier Series Coefficients With (K=20)');
grid on;grid minor;
subplot(3,3,6);
plot(y2.*abs(y2f));
title('Fourier Series Transform With (K=20)');
grid on;grid minor;
% ---------------------------------------------------------------
t3=-2:0.04:2;
y3=ones(1, size(t3,2)).*(t3>-1 & t3<1) + 0.*(t3<=-1 & t3>=1);
y3=repmat(y3, 1, 2);
y3f=fftshift(fft(y3));
subplot(3,3,7);
plot(y3);
title('Step Square pulse With (K=100)');
grid on;grid minor;
subplot(3,3,8);
stem(abs(y3f));
title('Fourier Series Coefficients With (K=100)');
grid on;grid minor;
subplot(3,3,9);
plot(y3.*abs(y3f));
title('Fourier Series Transform With (K=100)');
grid on;grid minor;