function[] = vars2Single()
    assignin('base','S',single(evalin('base','S')));
    assignin('base','Ez',single(evalin('base','Ez')));
    assignin('base','Hx',single(evalin('base','Hx')));
    assignin('base','Hy',single(evalin('base','Hy')));
    assignin('base','Cezhx',single(evalin('base','Cezhx')));
    assignin('base','Cezhy',single(evalin('base','Cezhy')));
    assignin('base','Chyez',single(evalin('base','Chyez')));
    assignin('base','Chxez',single(evalin('base','Chxez')));
    assignin('base','aex',single(evalin('base','aex')));
    assignin('base','aey',single(evalin('base','aey')));
    assignin('base','bex',single(evalin('base','bex')));
    assignin('base','bey',single(evalin('base','bey')));
    assignin('base','amx',single(evalin('base','amx')));
    assignin('base','amy',single(evalin('base','amy')));
    assignin('base','bmx',single(evalin('base','bmx')));
    assignin('base','bmy',single(evalin('base','bmy')));
    assignin('base','Psi_ezx',single(evalin('base','Psi_ezx')));
    assignin('base','Psi_ezy',single(evalin('base','Psi_ezy')));
    assignin('base','Psi_hyx',single(evalin('base','Psi_hyx')));
    assignin('base','Psi_hxy',single(evalin('base','Psi_hxy')));
    assignin('base','CPsi_ezx',single(evalin('base','CPsi_ezx')));
    assignin('base','CPsi_ezy',single(evalin('base','CPsi_ezy')));
    assignin('base','CPsi_hyx',single(evalin('base','CPsi_hyx')));
    assignin('base','CPsi_hxy',single(evalin('base','CPsi_hxy')));
end